services:
  encode:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app/image.jpg
        target: /app/image.jpg
      - type: bind
        source: .
        target: /app/output
    environment:
      - SECRET_DATA=hello, friend.
    entrypoint: ["python", "steganography.py", "encode"]

  decode:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./key.key
        target: /app/output/key.key
      - type: bind
        source: ./steganography.png
        target: /app/output/steganography.png
      - type: bind
        source: .
        target: /app/output
    entrypoint: ["python", "steganography.py", "decode"]
